name: diff_other_dir
description: diff on dir

inputs:
  subdir:
    required: true
outputs:
  diff-count:
    value: ${{ steps.diff.outputs.diff-count }}
    
runs:
  using: composite
  steps:
    - id: diff
      env:
        TARGET_BRANCH: ${{ github.base_ref }}
        SUBDIR: ${{ inputs.subdir }}
      run: |
        git fetch origin ${TARGET_BRANCH}
        count=`git diff origin/${TARGET_BRANCH} HEAD --name-only | grep -v ${SUBDIR} | wc -l`
        echo "::set-output name=diff-count::$(echo $count)"
      shell: bash
